schema_version = "1.0.0"
id = "wheel_o_matic"
version = "1.0.1"
name = "Wheel-O-Matic"
tagline = "Automatic wheel rotation in any direction"
maintainer = "TechArtToolBox"
type = "add-on"
website = "https://github.com/TechArtToolBox/wheel-o-matic/"
tags = ["Rigging","Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

